# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-vresion: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out do código do projeto
      - uses: actions/checkout@v2
      
      # Setup do Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with: 
          node-version: ${{ matrix.node-version }}
     
      # Instalando as dependências          
      - run: npm install
        
      # Executar testes
      - run: npm run cy:run
      
      # Gerar relatótio com Mochawesome
      - run: npm run report:merge
      - run: npm run report:mocha
        
      # Publicar relatório em HTML
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          BRANCH: gh-pages
          FOLDER: mochawesome-report
